name: C/C++ CI

on:
  push:
    branches: [ "vxr-ci" ]
  pull_request:
    branches: [ "vxr-ci" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make build=release -j
